"""empty message

Revision ID: 078231386f5e
Revises: 532e93bdd3d9
Create Date: 2023-11-17 18:18:33.754390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078231386f5e'
down_revision = '532e93bdd3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('ability')

    # ### end Alembic commands ###
