"""empty message

Revision ID: 27fc525c966c
Revises: 078231386f5e
Create Date: 2023-11-17 19:53:29.154087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fc525c966c'
down_revision = '078231386f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['trainer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###
