"""empty message

Revision ID: 340e07006f35
Revises: b8635f3ac545
Create Date: 2023-11-19 16:24:26.137254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340e07006f35'
down_revision = 'b8635f3ac545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
