"""empty message

Revision ID: 532e93bdd3d9
Revises: d3d61d8cfc7b
Create Date: 2023-11-16 14:05:38.099810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532e93bdd3d9'
down_revision = 'd3d61d8cfc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pokemon',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_name'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pokemon1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pokemon2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pokemon3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pokemon4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pokemon5', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pokemon6', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon1'], ['pokemon.pkmn_name'], name='team_pokemon1_fkey'),
    sa.ForeignKeyConstraint(['pokemon2'], ['pokemon.pkmn_name'], name='team_pokemon2_fkey'),
    sa.ForeignKeyConstraint(['pokemon3'], ['pokemon.pkmn_name'], name='team_pokemon3_fkey'),
    sa.ForeignKeyConstraint(['pokemon4'], ['pokemon.pkmn_name'], name='team_pokemon4_fkey'),
    sa.ForeignKeyConstraint(['pokemon5'], ['pokemon.pkmn_name'], name='team_pokemon5_fkey'),
    sa.ForeignKeyConstraint(['pokemon6'], ['pokemon.pkmn_name'], name='team_pokemon6_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_pkey')
    )
    op.drop_table('user_pokemon')
    # ### end Alembic commands ###
