"""empty message

Revision ID: 5b4255c44293
Revises: 
Create Date: 2023-11-20 12:40:24.182688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4255c44293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('pkmn_name', sa.String(), nullable=False),
    sa.Column('shiny_sprite_url', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('sp_atk', sa.Integer(), nullable=False),
    sa.Column('sp_def', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pkmn_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trainer_catch',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('catch', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['catch'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_catch')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
