"""empty message

Revision ID: 7f2472205ea4
Revises: 27fc525c966c
Create Date: 2023-11-19 10:23:58.714582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2472205ea4'
down_revision = '27fc525c966c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiny_sprite_url', sa.String(), nullable=False))
        batch_op.drop_column('shiny_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiny_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('shiny_sprite_url')

    # ### end Alembic commands ###
