"""empty message

Revision ID: b8635f3ac545
Revises: 7f2472205ea4
Create Date: 2023-11-19 11:20:23.621366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8635f3ac545'
down_revision = '7f2472205ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint('pokemon_trainer_id_fkey', type_='foreignkey')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('pokemon_trainer_id_fkey', 'user', ['trainer_id'], ['id'])

    # ### end Alembic commands ###
