"""empty message

Revision ID: d3d61d8cfc7b
Revises: 83f6e9464af0
Create Date: 2023-11-14 22:36:08.757352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d61d8cfc7b'
down_revision = '83f6e9464af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('shiny_url', sa.String(), nullable=False),
    sa.Column('pkmn_name', sa.String(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('sp_atk', sa.Integer(), nullable=False),
    sa.Column('sp_def', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pkmn_name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon1', sa.String(), nullable=False),
    sa.Column('pokemon2', sa.String(), nullable=False),
    sa.Column('pokemon3', sa.String(), nullable=False),
    sa.Column('pokemon4', sa.String(), nullable=False),
    sa.Column('pokemon5', sa.String(), nullable=False),
    sa.Column('pokemon6', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon1'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['pokemon2'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['pokemon3'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['pokemon4'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['pokemon5'], ['pokemon.pkmn_name'], ),
    sa.ForeignKeyConstraint(['pokemon6'], ['pokemon.pkmn_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
